M48
; DRILL file {KiCad 9.0.7} date 2026-01-19T17:27:04+0000
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-01-19T17:27:04+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0827
%
G90
G05
T1
X4.3701Y-3.4547
X4.685Y-3.9764
X6.8898Y-3.9764
X7.2736Y-3.4547
M30
