M48
; DRILL file {KiCad 8.0.1} date 2025-11-12T10:25:38+0000
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-11-12T10:25:38+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0827
%
G90
G05
T1
X4.2717Y-3.7303
X4.7638Y-0.7185
X6.624Y-0.748
X7.3327Y-3.7402
M30
